#
#此文件包含用于自定义站点的配置标志
#
#您的网站名称（显示在标题中）
姓名：你的名字
#简短的个人简介或描述（显示在标题中）
描述： 来自某个地方的 Web 开发人员
#您的头像或个人资料图片的 URL（您可以使用您的 GitHub 个人资料图片）
头像：https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
#
#以下标志是可选的
#
#在页脚中包含您输入的每个用户名的图标
页脚链接：
  运球：
  电子邮件：
  脸书：
  Flickr：
  GitHub：Barryclark/Jekyll-Now
  Instagram：
  LinkedIn：
  Pinterest：
  rss：# 只需在此处键入任何内容即可获得有效的 RSS 图标
  推特：Jekyllrb
  stackoverflow：# 你的 stackoverflow 配置文件，例如 “users/50476/bart-kiers”
  YouTube：#频道/<your_long_string>或用户/<用户名>
  GooglePlus：#您的个人资料用户名中 plus.google.com/ 之后的任何内容
#输入您的 Disqus 短名称（不是您的用户名）以启用对帖子的评论
#您可以在 Disqus 帐户的“设置”页面上找到您的短名称
论文：
#输入您的谷歌分析网络跟踪代码（例如UA-2110908-2）以激活跟踪
google_analytics：
#您的网站网址（例如 http://barryclark.github.io 或 http://www.barryclark.co）
#用于站点地图.xml和您的 RSS 提要
网址：
#如果你在 GitHub 页面上的项目存储库中托管网站
# （http://yourusername.github.io/repository-name）
# 而不是您的用户存储库 （http://yourusername.github.io）
# 然后在此处添加基本网址，如下所示：“/repository-name”
基本网址：""
#
# ！！您无需更改下面的任何配置标志！
#

降价：红地毯
荧光笔：侏儒
永久链接： /：title/

#杰基尔的发布 现在你正在使用
版本： v1.1.0

#Jekyll 3 现在只支持 Kramdown for Markdown
克拉姆当：
  #使用 GitHub 风格的降价，包括三反引号围栏代码块
  输入：GFM
  #Jekyll 3 和 GitHub Pages 现在只支持 rouge 进行语法高亮
  syntax_highlighter：胭脂
  syntax_highlighter_opts：
    #使用现有的 pygments 语法突出显示 css
    css_class：“亮点”

#设置 Sass 部分目录，因为我们正在使用@imports
屁股：
  样式： ：展开 # 您可能更喜欢使用 ：压缩
#使用以下插件
宝石：
  - 杰基尔站点地图 # 使用官方 Jekyll 站点地图 gem 创建站点地图
  - jekyll-feed # 使用官方 Jekyll feed gem 创建 Atom 提要
#从生产_site中排除这些文件
不包括：
    - 宝石文件
    - Gemfile.lock
    - 许可证
    - README.md
    - 别名记录
